" **************************************************************************** "
"                                                                              "
"                                                         :::      ::::::::    "
"    .vimrc                                             :+:      :+:    :+:    "
"                                                     +:+ +:+         +:+      "
"    By: Belotte <fbellott@student.42.fr>           +#+  +:+       +#+         "
"                                                 +#+#+#+#+#+   +#+            "
"    Created: 2015/12/06 17:03:23 by Belotte           #+#    #+#              "
"    Updated: 2016/08/08 11:04:16 by fbellott         ###   ########.fr        "
"                                                                              "
" **************************************************************************** "

set background=dark
colorscheme mustang

syntax on
set colorcolumn=81
set number
set tabstop=4
filetype plugin indent on
set smartindent
set autoindent
set cindent
set backspace=indent,eol,start
set showmode
set ruler
set showcmd
execute pathogen#infect('stuff/{}')
set sessionoptions-=options
set autoread
hi SpecialKey ctermfg=66 guifg=#649A9A ctermbg=NONE
hi Nontext ctermfg=66 guifg=#649A9A ctermbg=NONE
set listchars=eol:$,tab:\|\ ,trail:.
set list

hi! sp ctermbg=NONE guibg=NONE ctermfg=red guifg=red

autocmd BufRead 			* match sp /^[^(\#)]]]\ \{2,}\|\t\+\n\|\ \+\n/
autocmd BufRead 			*.[ch] match sp /^[^(\/\*)]]]\ \{2,}\|\t\+\n\|\ \+\n/
