#!/bin/bash 

#****************************************************************************#
#*																			*#
#*														:::		 ::::::::	*#
#*	install_brew									  :+:	   :+:	  :+:	*#
#*													+:+ +:+			+:+		*#
#*	by: Belotte <belotte1355@gmail.com>			  +#+  +:+		 +#+		*#
#*												+#+#+#+#+#+	  +#+			*#
#*	Created: 2015/06/10 21:05:19 by Belotte			 #+#	#+#				*#
#*	Updated: 2013/06/10 21:05:19 by Belotte			 ###  ########.fr		*#
#*																			*#
#****************************************************************************#

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
