#!/bin/bash 

#****************************************************************************#
#*																			*#
#*														:::		 ::::::::	*#
#*	Create_Makefile									  :+:	   :+:	  :+:	*#
#*													+:+ +:+			+:+		*#
#*	by: Belotte <belotte1355@gmail.com>			  +#+  +:+		 +#+		*#
#*												+#+#+#+#+#+	  +#+			*#
#*	Created: 2015/06/20 15:02:47 by Belotte			 #+#	#+#				*#
#*	Updated: 2015/06/20 15:02:47 by Belotte			 ###  ########.fr		*#
#*																			*#
#****************************************************************************#

s_dir='srcs/'
o_dir='objs/'
i_dir='-I includes/'
main='main.c'
home=`cd; pwd`
files=`ls srcs/*.c 2> /dev/null | cut -d'/' -f2 | tr '\n' ' '`
if [[ $files == "" ]]; then
	files=`ls *.c | tr '\n' ' '`
	s_dir=''
	o_dir=''
	i_dir=''
	main=''
fi

if [[ ! -d objs ]]; then
	mkdir objs
fi

rules='$(CC) $(FLAGS) $(LIB) $^ '"$main"' -o $@'

if [[ "$1" != '' ]]; then
	name=$1
	if [[ "$2" == 'lib' ]]; then
		rules='ar rc $(NAME) $(OBJS); ranlib $(NAME)'
	fi
else
	name='run'
fi

echo 'NAME	= '"$name"'
CC		= gcc
S_DIR	= '"$s_dir"'
O_DIR	= '"$o_dir"'
I_DIR	= -I '"$home"'/Documents/Programs/C/Lib/includes '"$i_dir"'
LIB		= '"$home"'/Documents/Programs/C/Lib/libft.a
FLAGS	= -Wall -Wextra -Werror $(I_DIR)
FILES	= '"$files"'
SRC		= $(addprefix $(S_DIR),$(FILES))
OBJS	= $(addprefix $(O_DIR),$(FILES:.c=.o))
RM		= rm -f

all: 		$(NAME)

$(NAME): 	$(OBJS)
	'"$rules"'
	@echo "Done."

$(O_DIR)%.o:		$(S_DIR)%.c
	$(CC) $(FLAGS) -c $< -o $@

clean:
	@$(RM) $(OBJS)

fclean: 	clean
	@$(RM) $(NAME)
	@echo "Clear."

re:			fclean all' > Makefile
