#!/bin/bash

# Makefile_Creator					-> generate a Makefile for a program
# Makefile_Creator <library_name>	-> generate a Makefile to compile a library

# Don't touch !
white='\033[0;1m'
black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
pink='\033[0;35m'
cyan='\033[0;36m'
grey='\033[0;37m'

s_dir='srcs/'
o_dir='objs/'
i_dir='-I includes/'
main='main.c'
mainodir='$(O_DIR)main.o'
home=`cd; pwd`
lib=`ls *.a 2> /dev/null | cut -d'.' -f1 | cut -d'b' -f2`
lib=`echo $lib`
main_rule="\n"'$(O_DIR)main.o:	main.c'"\n\t"'@echo "'$yellow'$<'$grey'"\n\t@echo "↪︎-   '$green'$@'$white'"'"\n\t"'@$(CC) $(FLAGS) -c $< -o $@'"\n"
files=`ls srcs/*.c 2> /dev/null | cut -d'/' -f2 | tr '\n' ' '`
if [[ $files == "" ]]; then
	files=`ls *.c | tr '\n' ' '`
	s_dir=''
	o_dir=''
	i_dir=''
	main=''
	main_rule=''
	mainodir=''
else
	if [[ ! -d objs ]]; then
		mkdir objs
	fi
fi


rules='$(CC) $(FLAGS) $(LIBS) $^ -o $@'

if [[ "$1" != '' ]]; then
	name=$1
	rules='ar rc $(NAME) $(OBJS); ranlib $@'
	main_rule=''
	mainodir=''
else
	name='run'
fi

#I_DIR	= -I '"$home"'/Documents/Programs/C/Lib/includes '"$i_dir"'
#LIB		= '"$home"'/Documents/Programs/C/Lib/libft.a
#LIBS_DIR= -L '"$libs"' -I '"$libs"'

echo 'SHELL	= bash
NAME	= '"$name"'
CC		= gcc
S_DIR	= '"$s_dir"'
O_DIR	= '"$o_dir"'
I_DIR	= '"$i_dir"'
CFLAGS	= -Wall -Wextra -Werror $(I_DIR) $(LIBS_DIR)
FILES	= '"$files"'
SRC		= $(addprefix $(S_DIR),$(FILES))
OBJS	= $(addprefix $(O_DIR),$(FILES:.c=.o))
COUNTER	= $$(ls srcs/*.c | wc -l | tr -s " " "." | cut -d"." -f2)
RM		= rm -f

all:		header $(NAME)

$(NAME): 	$(OBJS) $(O_DIR)main.o
	@tput cnorm
	@echo ""
	@echo ""
	@$(CC) $^ -o $@ $(CFLAGS) || (tput cnorm && exit 1)
	@echo "./[0;34m$(NAME)[0;38m created."
	@tput cnorm

$(O_DIR)%.o:		$(S_DIR)%.c
	@$(CC) -c $< -o $@ $(CFLAGS) || (tput cnorm && exit 1)
	@echo -n "."

$(O_DIR)main.o: main.c
	@$(CC) -c $< -o $@ $(CFLAGS) || (tput cnorm && exit 1)
	@echo -n "."

clean:
	@$(RM) $(OBJS) $(O_DIR)main.o

fclean: 	clean
	@$(RM) $(NAME)
	@echo "[0;1mClear."

re:			fclean all

header:
	@tput civis
	@clear
	@echo ""
	@echo "                     [0;34m  __  __       _        _____ _ _      "
	@echo "                      |  \/  | __ _| | _____|  ___(_) | ___ "
	@echo "                      | |\/| |/ _\` | |/ / _ \ |_  | | |/ _ \\"
	@echo "                      | |  | | (_| |   <  __/  _| | | |  __/"
	@echo "                      |_|  |_|\__,_|_|\_\___|_|   |_|_|\___|"
	@echo ""
	@echo ""
	@echo "[0;38mCompiling $(NAME)"
	@echo "[0;31m["
	@tput cup 9 $$(($(COUNTER) + 2))
	@echo "][0;36m"
	@tput cup 9 1

.PHONY: re clean fclean all' > Makefile
