#!/bin/bash 

#****************************************************************************#
#*																			*#
#*														:::		 ::::::::	*#
#*	Rename											  :+:	   :+:	  :+:	*#
#*													+:+ +:+			+:+		*#
#*	by: Belotte <belotte1355@gmail.com>			  +#+  +:+		 +#+		*#
#*												+#+#+#+#+#+	  +#+			*#
#*	Created: 2015/06/21 13:12:56 by Belotte			 #+#	#+#				*#
#*	Updated: 2015/06/21 13:12:56 by Belotte			 ###  ########.fr		*#
#*																			*#
#****************************************************************************#

i=1

if [[ $# -ne 2 ]]; then
	echo "Usage: Rename <Name> <Season>"

	exit 1
fi

for file in *; do
	if [[ $i -lt 10 ]]; then
		mv "$file" "$1 $2x0$i.${file##*.}"
	else
		mv "$file" "$1 $2x$i.${file##*.}"
	fi

	((i+=1))
done

exit 0